apiVersion: v1
data:
  config.yaml: |-
    {{ .Values.config | toYaml | indent 4 | trim }}
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}